# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.hostname = "roxs"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.disk :disk, size: "50GB", primary: true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "2"
     vb.name = "roxs"
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install wget curl git vim make tree ca-certificates gnupg lsb-release -y 
      apt-get install -y ssh net-tools nano nginx
  SHELL
end
